### ISSUE TITLE
Fails to run `tapioca init` with error: `Cannot extract source from uninitialized Source::Buffer`

### ISSUE THREAD

**Issue by jamietanna** [Shopify/rbi#178]
On a Rails 6.1.7 codebase, with the following Sorbet gems:

```
    sorbet (0.5.10201)
      sorbet-static (= 0.5.10201)
    sorbet-runtime (0.5.10201)
    sorbet-static (0.5.10201-universal-darwin-14)
    sorbet-static (0.5.10201-universal-darwin-15)
    sorbet-static (0.5.10201-universal-darwin-16)
    sorbet-static (0.5.10201-universal-darwin-17)
    sorbet-static (0.5.10201-universal-darwin-18)
    sorbet-static (0.5.10201-universal-darwin-19)
    sorbet-static (0.5.10201-universal-darwin-20)
    sorbet-static (0.5.10201-universal-darwin-21)
    sorbet-static (0.5.10201-universal-darwin-22)
    sorbet-static (0.5.10201-x86_64-linux)
    sorbet-struct-comparable (1.2.0)
      sorbet-runtime (>= 0.5)

    ast (2.4.2)
    parser (3.2.2.1)
      ast (~> 2.4.1)
```

Trying to install tapioca v0.11.6 and then running `tapioca init` results in:

```
/usr/local/rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/source/buffer.rb:146:in `source': Cannot extract source from uninitialized Source::Buffer (RBI::UnexpectedParserError)
```

It appears that this was due to tapioca expecting a newer version of `parser`, because running `bundle update parser`, led to the following versions:

```
    parser (3.2.2.1)
      ast (~> 2.4.1)
```

Which then led me to #139, and following the steps in there to bump `unparser` has allowed `tapioca init` to work correctly.

<details>

<summary>Full stacktrace</summary>

```
bundle exec tapioca init
        skip  sorbet/config
      create  sorbet/tapioca/config.yml
      create  sorbet/tapioca/require.rb
      create  bin/tapioca
Retrieving index from central repository... Done
Listing gems from Gemfile.lock... Done
Removing annotations for gems that have been removed...  Nothing to do
Fetching gem annotations from central repository...

##################################
### RBI::Parser internal error ###
##################################

There was an internal parser error while processing this source.

Error: Cannot extract source from uninitialized Source::Buffer while parsing -::-::

<no source>

Please open an issue at https://github.com/Shopify/rbi/issues/new.

##################################

Traceback (most recent call last):
        54: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
        53: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
        52: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/tapioca:23:in `<main>'
        51: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/tapioca:23:in `load'
        50: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/exe/tapioca:25:in `<top (required)>'
        49: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        48: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        47: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        46: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        45: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:29:in `init'
        44: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        43: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        42: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/runtime/trackers.rb:26:in `with_trackers_enabled'
        41: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:31:in `block in init'
        40: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        39: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        38: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        37: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        36: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:328:in `annotations'
        35: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        34: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        33: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca.rb:22:in `silence_warnings'
        32: from /Users/jamietanna/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
        31: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca.rb:23:in `block in silence_warnings'
        30: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:329:in `block in annotations'
        29: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        28: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        27: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:40:in `execute'
        26: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        25: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        24: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:126:in `fetch_annotations'
        23: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:126:in `select'
        22: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:126:in `block in fetch_annotations'
        21: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        20: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        19: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:137:in `fetch_annotation'
        18: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        17: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        16: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:228:in `merge_files'
        15: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:228:in `each'
        14: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:229:in `block in merge_files'
        13: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        12: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        11: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/rbi-0.0.16/lib/rbi/parser.rb:71:in `parse_string'
        10: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
         9: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
         8: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/rbi-0.0.16/lib/rbi/parser.rb:87:in `parse_string'
         7: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
         6: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
         5: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/rbi-0.0.16/lib/rbi/parser.rb:105:in `parse'
         4: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/unparser-0.5.5/lib/unparser.rb:108:in `parse_with_comments'
         3: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/base.rb:206:in `parse_with_comments'
         2: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/base.rb:186:in `parse'
         1: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/lexer.rb:10890:in `source_buffer='
/Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/source/buffer.rb:146:in `source': Cannot extract source from uninitialized Source::Buffer (RuntimeError)
        54: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
        53: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
        52: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/tapioca:23:in `<main>'
        51: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/bin/tapioca:23:in `load'
        50: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/exe/tapioca:25:in `<top (required)>'
        49: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        48: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        47: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        46: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        45: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:29:in `init'
        44: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        43: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        42: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/runtime/trackers.rb:26:in `with_trackers_enabled'
        41: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:31:in `block in init'
        40: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        39: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        38: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        37: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        36: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:328:in `annotations'
        35: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        34: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        33: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca.rb:22:in `silence_warnings'
        32: from /Users/jamietanna/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
        31: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca.rb:23:in `block in silence_warnings'
        30: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/cli.rb:329:in `block in annotations'
        29: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        28: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        27: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:40:in `execute'
        26: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        25: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        24: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:126:in `fetch_annotations'
        23: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:126:in `select'
        22: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:126:in `block in fetch_annotations'
        21: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        20: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        19: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:137:in `fetch_annotation'
        18: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        17: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        16: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:228:in `merge_files'
        15: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:228:in `each'
        14: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.6/lib/tapioca/commands/annotations.rb:229:in `block in merge_files'
        13: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        12: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
        11: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/rbi-0.0.16/lib/rbi/parser.rb:71:in `parse_string'
        10: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
         9: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
         8: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/rbi-0.0.16/lib/rbi/parser.rb:87:in `parse_string'
         7: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
         6: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10201/lib/types/private/methods/_methods.rb:272:in `bind_call'
         5: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/rbi-0.0.16/lib/rbi/parser.rb:105:in `parse'
         4: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/unparser-0.5.5/lib/unparser.rb:108:in `parse_with_comments'
         3: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/base.rb:206:in `parse_with_comments'
         2: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/base.rb:186:in `parse'
         1: from /Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/lexer.rb:10890:in `source_buffer='
/Users/jamietanna/.rvm/gems/ruby-2.7.5/gems/parser-2.7.1.2/lib/parser/source/buffer.rb:146:in `source': Cannot extract source from uninitialized Source::Buffer (RBI::UnexpectedParserError)
```

</details>

**Comment by jamietanna** [comment]
Adding this to document it for future folks who may hit this issue - not sure if maybe `parser` should be added as a dependency?
